# Generated by Django 5.2.8 on 2025-11-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khulnatourgroup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(null=True)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
        ),
    ]
